### ISSUE TITLE
Change borderRadius to circle

### ISSUE THREAD

**Issue by dabit3** [wusuopu/react-native-fscalendar#3]
Is there any way to change the borderRadius to be a circle for the chosen dates?

Thanks.

**Comment by dabit3** [comment]
I see the `cellShapeDates`, does this have anything to do with it?

**Comment by wusuopu** [comment]
@dabit3 

it can use `cellShapeDates` props. Example: `cellShapeDates = {'2017-05-06': 0, '2017-05-07': 1}`

the value is 0, it will display as rectangle. and the value is 1, it will display as circle.

see https://github.com/wusuopu/react-native-fscalendar/blob/master/Demo/src/example6.js#L44
